# Generated by Django 5.0 on 2023-12-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0004_event_event_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
