# Generated by Django 5.0 on 2023-12-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0004_event_event_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
