# Generated by Django 5.0 on 2023-12-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0005_remove_event_location_event_latitude_event_longitude'),
        ('m_app', '0007_alter_event_user'),
    ]

    operations = [
    ]
