# Generated by Django 5.0 on 2023-12-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0008_merge_20231221_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
