# Generated by Django 5.0 on 2023-12-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0010_remove_event_latitude_remove_event_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
