# Generated by Django 5.0 on 2023-12-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0012_event_image_alter_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('social', 'Social Event'), ('educational', 'Educational Event'), ('hackathon', 'Hackathon'), ('offer', 'Offer'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
