# Generated by Django 5.0 on 2023-12-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0013_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
