# Generated by Django 5.0 on 2023-12-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0017_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_datetime',
            new_name='date',
        ),
    ]
