# Generated by Django 5.0 on 2023-12-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0018_rename_event_datetime_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='eventType',
        ),
    ]
