# Generated by Django 5.0 on 2023-12-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0019_rename_event_type_event_eventtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
