# Generated by Django 5.0 on 2023-12-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0020_remove_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventType',
            new_name='EventType',
        ),
    ]
