# Generated by Django 5.0 on 2023-12-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0021_rename_eventtype_event_eventtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='event_datetime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='EventType',
            new_name='event_type',
        ),
    ]
