# Generated by Django 5.0 on 2023-12-24 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_app', '0022_rename_date_event_event_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='EventType',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_datetime',
            new_name='date',
        ),
    ]
